name: Celcat → Discord (20:00 Paris)

on:
  schedule:
    # Exécute TOUTES les heures pour ne plus gérer l'heure d'été/hiver.
    - cron: "0 * * * *"
  workflow_dispatch: {}  # lancement manuel possible

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python deps
        run: |
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Run script (guard 20:00 Paris inside script)
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          CELCAT_LIST_URL: ${{ secrets.CELCAT_LIST_URL }}
          TZ_NAME: ${{ secrets.TZ_NAME || 'Europe/Paris' }}
          POST_AT_HOUR: "20"
        run: python celcat_html_to_discord.py
